apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  name: mysql-vm
  namespace: ns01
  labels:
    vm-selector: mysql-vm-lb-azvo
    mysql-lb: vm-lb-selector
    topology.kubernetes.io/zone: zone1
spec:
  className: best-effort-small
  # Friendly image name: noble-server-cloudimg-amd64
  imageName: vmi-901d933a474152647
  storageClass: cluster-wld01-01a-vsan-storage-policy
  powerState: PoweredOn
  bootstrap:
    cloudInit:
      rawCloudConfig:
        name: mysql-vm-bootstrap-secret
        key: user-data