apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJrYXRicm9va2ZpZWxkIiwicGFzc3dvcmQiOiJMYW1lcmthOCEiLCJhdXRoIjoiYTJGMFluSnZiMnRtYVdWc1pEcE1ZVzFsY210aE9DRT0ifX19
